version: "3.7"

services:
  frontend:
    build:
      context: "../apps/2048"
    ports:
      - "8888:80"  
  ngrok:
    image: wernight/ngrok
    ports:
      - "4040:4040"
    command: ["ngrok", "http", "frontend:80"]
