version: "3.9"

services:
  frontend:
    build:
      context: "../apps/dwg-web"
    ports:
      - "8888:80"  
  ngrok:
    image: wernight/ngrok
    ports:
      - "4040:4040"
    command: ["ngrok", "http", "frontend:80"]
