version: "3.9"

services:

  wordpress:
    container_name: wordpress
    image: wordpress:php7.4
    # image: wordpress:php8.1
    restart: always
    depends_on:
      - db
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_HOST: "db:3306"
      WORDPRESS_DB_USER: "whale"
      WORDPRESS_DB_PASSWORD: "!My7xJ(!d~z9Mw&Sw=uN"
      WORDPRESS_DB_NAME: "wpdb"
    volumes:
      - /var/wordpress/data:/var/www/html

  db:
    container_name: mysql-db
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: "wpdb"
      MYSQL_USER: "whale"
      MYSQL_PASSWORD: "!My7xJ(!d~z9Mw&Sw=uN"
      MYSQL_ROOT_PASSWORD: "rootpassword123"
    volumes:
      - /var/mysql/data:/var/lib/mysql

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:5.1.3
    restart: always
    ports:
      - 127.0.0.1:8085:80
    environment:
      - PMA_HOST=db   