version: "3.7"

services:
  postgres:
    container_name: postgres_container
    image: postgres:10
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user1}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-pass123}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5446:5432"
    networks:
      - postgres
    restart: always

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgres
    restart: always

networks:
  postgres:

volumes:
  postgres:
  pgadmin:
